apiVersion: v1
data:
  config.js: |
    window._env_ = {
      REACT_APP_API_URL: "http://localhost:8080"
    };
kind: ConfigMap
metadata:
  name: dev-frontend-config
  namespace: dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: dev-frontend-service
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: dev-frontend-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: anish60/frontend
        name: frontend
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html/config.js
          name: config-volume
          subPath: config.js
      volumes:
      - configMap:
          name: dev-frontend-config
        name: config-volume
