apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
      initContainers:
      - name: wait-for-db
        image: curlimages/curl:8.0.1
        command:
          - sh
          - -c
          - |
            echo "Waiting for Cloud Native PG database to be healthy..."
            until curl --silent --fail http://cloudnative-pg-service:8080/health; do
              echo "Database not ready - retrying in 5 seconds..."
              sleep 5
            done
            echo "Cloud Native PG database is up and running."
      containers:
      - name: backend
        image: anish60/backend:latest
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: database-credentials
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
