apiVersion: v1
data:
  DB_HOST: bXktcG9zdGdyZXNxbC1ydy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_NAME: dG9kb3M=
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_PORT: NTQzMg==
  DB_USER: YW5pc2g=
kind: Secret
metadata:
  creationTimestamp: null
  name: database-credentials
