apiVersion: v1
kind: Secret
metadata:
  name: production-devops-project-secret
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/anishbista60/Production-Devops-project.git               
  password: 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              
  username: production-app                                   
  