apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  log.level: info
  registries.conf: |
    registries:
    - name: Azure Container Registry
      prefix: todoappproject.azurecr.io
      api_url: https://todoappproject.azurecr.io
      ping: yes
      credentials: ext:/app/acr.sh
      credsexpire: 10h
