apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
#- service-monitor.yaml
- argocd-image-updater-acr-configmap.yaml
#- ingress.yaml
- argocd-github-secret.yaml

# Azure container registry configuration
patches:
- path: argocd-image-updater-configmap.yaml
- path: patch-argocd-image-updater-deployment.yaml
- path: argocd-cm.yaml