apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cloudnative-pg
    releaseName: cloudnative-pg
    namespace: cnpg
    version: 0.23.0
    repo: https://cloudnative-pg.github.io/charts
    valuesFile: values.yaml
    includeCRDs: true
resources:
  - namespace.yaml
