apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql
  namespace: postgres          
spec:
  instances: 1           
  storage:
    size: 1Gi
  monitoring:                     
    enablePodMonitor: false     
  bootstrap:
    initdb:
      database: todos
      owner: anish
      secret:
        name: postgresql-credentials
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: postgresql-init-scripts
          key: configmap.sql