apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            cpu: "200m"   
            memory: "200Mi"  
          limits:
            memory: "200Mi"  