apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

- azure-vault-auth-secret.yaml
- azure-vault-auth.yaml
- secret.yaml

namespace: dev
namePrefix: dev-

patches:
- path: backend-dev-deploy-patch.yaml
