apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

- azure-vault-credential.yaml
- azure-vault-auth.yaml
- secret.yaml
- hpa.yaml

namespace: dev
patches:
- path: backend-dev-deploy-patch.yaml
