apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret                               # Name of the external secrets. will be same as the service name  
spec:
  secretStoreRef:
    name: dev-azure-store                                      # (no need to change) Reference to SecretStore configured for Azure Key Vault
    kind: SecretStore
  target:
    name: backend-database-credentials                             # Kubernetes Secret name that will be created
  data:
    - secretKey: DB_HOST                         # Key in the Kubernetes Secret 
      remoteRef:
        key: db-host                             # Aure key vault secret key 
    - secretKey: DB_USER
      remoteRef:
        key: db-user    
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-password
    - secretKey: DB_NAME
      remoteRef:
        key: db-name
    - secretKey: DB_PORT
      remoteRef:
        key: db-port     
