apiVersion: v1
data:
  ClientID: OTYyYWI4ZWMtMGYwZi00MzMyLTg0ZDQtYWI0ODYwNzA1NDFkCg==
  ClientSecret: Lk5YOFF+QWllT0llSFhUeWs1SmV4Z34ybXRnVkw2T1Ywa3JGUGJ5aAo=
kind: Secret
metadata:
  name: dev-azure-secret-sp
  namespace: dev
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: dev-backend-service
  namespace: dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: dev-backend-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: backend-database-credentials
        image: todoappproject.azurecr.io/backend:a9d8a5073b10ec05ef5d6567b3b9b362ba740144
        name: backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      initContainers:
      - command:
        - sh
        - -c
        - |
          until pg_isready -h my-postgresql-rw.postgres.svc.cluster.local -p 5432; do
            echo "Waiting for PostgreSQL database to be ready..."
            sleep 5
          done
          echo "PostgreSQL database is up and running."
        image: postgres:15
        name: wait-for-db
        securityContext:
          runAsUser: 999
      securityContext:
        runAsNonRoot: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-backend-secret
  namespace: dev
spec:
  data:
  - remoteRef:
      key: db-host
    secretKey: DB_HOST
  secretStoreRef:
    kind: SecretStore
    name: dev-azure-store
  target:
    name: backend-database-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dev-azure-store
  namespace: dev
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: ClientID
          name: dev-azure-secret-sp
        clientSecret:
          key: ClientSecret
          name: dev-azure-secret-sp
      tenantId: c22d1d63-4b94-4bdd-94c8-b2ee397929f7
      vaultUrl: https://todo-vault-prod.vault.azure.net
