apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Pod-level security context to enforce non-root execution
      securityContext:
        runAsNonRoot: true
      containers:
      - name: frontend
        image: your-frontend-image:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
