apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: frontend
        image: anish60/frontend:latest
        ports:
          - containerPort: 80
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
