apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      containers:
      - name: frontend
        image: todoappproject.azurecr.io/frontend:4a180c0a987fb2a26a1a0719dcd6db0edd8c4b7c
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: https://todoback.anishbista.xyz
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: config-volume
        configMap:
          name: frontend-config