apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod
namePrefix: prod-

patchesStrategicMerge:
  - backend-prod-deploy-patch.yaml
  - ingress-prod-patch.yaml