apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
  namespace: postgres
data:
  configmap.sql: |  
    -- Create table in public schema
    CREATE TABLE IF NOT EXISTS public.todos (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        completed BOOLEAN DEFAULT FALSE
    );

    -- Grant permissions to anish user on the table
    GRANT SELECT, INSERT, UPDATE, DELETE 
    ON ALL TABLES IN SCHEMA public 
    TO anish;

    -- Grant permissions on the sequence used for auto-incrementing IDs
    GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.todos_id_seq TO anish;
