apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
  namespace: postgres
data:
  configmap.sql: |    
    CREATE TABLE todos (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        completed BOOLEAN DEFAULT FALSE
    );
