apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-user-secret     
  namespace: postgres                            
spec:
  secretStoreRef:
    name: azure-store                                     
    kind: SecretStore
  target:
    name: postgresql-credentials                             
  data:
    - secretKey: username                         
      remoteRef:
        key: username                             
    - secretKey: password
      remoteRef:
        key: password    
