apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: 
    notifications.argoproj.io/subscribe.on-sync-failed.slack: 
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-deploy/backend/overlays/dev
    repoURL: git@github.com:enkryptai/enkryptai-apiaas.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
