apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: notification
    notifications.argoproj.io/subscribe.on-sync-failed.slack: notification
    notifications.argoproj.io/subscribe.on-delete.slack: notification
    argocd-image-updater.argoproj.io/image-list: backend=todoappproject.azurecr.io/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-deploy/backend/overlays/dev
    repoURL: https://github.com/anishbista60/Production-Devops-project.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
