apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatewayapi-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: notification
    notifications.argoproj.io/subscribe.on-sync-failed.slack: notification
    notifications.argoproj.io/subscribe.on-delete.slack: notification
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-deploy/gateway-api/dev
    repoURL: https://github.com/anishbista60/Production-Devops-project.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true