apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync: "slack"
    notifications.argoproj.io/subscribe.on-sync-failed: "slack"
    notifications.argoproj.io/subscribe.on-delete: "slack"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: platform-apps/ingress-controller
    repoURL: https://github.com/anishbista60/Production-Devops-project.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
