apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              memory: "200Mi"
