apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: dev
namePrefix: dev-

patches:
  - path: frontend-dev-deploy-patch.yaml  # Add 'path' and ensure correct file location
    target:
      kind: Deployment
      name: frontend-deployment
