apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - config.yaml
namespace: dev
namePrefix: dev-

patches:
  - path: frontend-dev-deploy-patch.yaml  
    target:
      kind: Deployment
      name: frontend-deployment
