name: Build, Scan & Push Docker Image for backend

on:
  push:
    branches: [ main ]
    paths:
      - 'app/backend/**'

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}  
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        working-directory: app/backend
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.sha }} .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}
          # Exit with code 1 if vulnerabilities of HIGH severity or above are found
          exit-code: '0'
          severity-threshold: 'HIGH'

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}
